# Generated by Django 5.0 on 2024-01-26 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
        ('supplier', '0002_alter_supplier_nomor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('ppn', models.PositiveIntegerField(default=0)),
                ('diskon', models.PositiveIntegerField(default=0)),
                ('dibayar', models.PositiveIntegerField(default=0)),
                ('sisa', models.PositiveIntegerField(default=0)),
                ('kembali', models.PositiveIntegerField(default=0)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('kredit', 'Kredit')], default='tunai', max_length=8)),
                ('lunas', models.BooleanField(default=False)),
                ('tempo', models.PositiveSmallIntegerField(default=3)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('dibayar', models.PositiveIntegerField(default=0)),
                ('sisa', models.PositiveIntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('pembayaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hutang_pembayaran', to='pembelian.pembayaran')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pembelian_supplier', to='supplier.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pembelian_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='pembelian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_pembelian', to='pembelian.pembelian'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.PositiveIntegerField(default=0)),
                ('diskon', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_item_barang', to='barang.barang')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_item_pembelian', to='pembelian.pembelian')),
            ],
        ),
    ]
