# Generated by Django 5.0 on 2024-01-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populate_pembelian_supplier', to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10, unique=True)),
                ('metode', models.CharField(choices=[('tunai', 'Tunai'), ('kredit', 'Kredit')], default='tunai', max_length=100)),
                ('diskon', models.PositiveIntegerField()),
                ('ppn', models.PositiveIntegerField()),
                ('total_ppn_discount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('dibayar', models.PositiveIntegerField()),
                ('kembali', models.PositiveIntegerField()),
                ('pembelian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_pembayaran_pembelian', to='pembelian.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskon', models.PositiveIntegerField()),
                ('harga_supplier', models.PositiveIntegerField()),
                ('jumlah', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('keterangan', models.CharField(max_length=200)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populate_item_barang', to='barang.barang')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populate_item_pembelian', to='pembelian.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10, unique=True)),
                ('tempo', models.PositiveIntegerField()),
                ('sisa', models.PositiveIntegerField()),
                ('pembayaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_hutang_pembayaran', to='pembelian.pembayaran')),
                ('pembelian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_hutang_pembelian', to='pembelian.pembelian')),
            ],
        ),
    ]
