# Generated by Django 5.0 on 2024-01-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='total_ppn_discount',
        ),
    ]
