# Generated by Django 5.0 on 2024-01-27 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
        ('pembelian', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retur_pembelian_pembelian', to='pembelian.pembelian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_return_pembelian_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturItemPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('alasan', models.CharField(blank=True, max_length=225, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_retur_item_pembelian_barang', to='barang.barang')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_retur_item_pembelian_item', to='pembelian.item')),
                ('retur_pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_retur_item_pembelian_retur_pembelian', to='pembelian.returpembelian')),
            ],
            options={
                'unique_together': {('retur_pembelian', 'barang', 'item')},
            },
        ),
    ]
