# Generated by Django 5.0 on 2024-01-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0002_remove_pembayaran_total_ppn_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='sisa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='tempo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
