# Generated by Django 5.0 on 2024-01-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0003_pembayaran_sisa_pembayaran_tempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hutang',
        ),
    ]
