# Generated by Django 5.0 on 2024-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0004_delete_hutang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='tanggal_jatuh_tempo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
