# Generated by Django 5.0 on 2024-01-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0004_alter_returpembelian_tanggal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='returitempembelian',
            unique_together=set(),
        ),
    ]
