# Generated by Django 5.0 on 2024-01-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0005_pembayaran_tanggal_jatuh_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=10, unique=True)),
                ('tanggal', models.DateField()),
                ('jumlah', models.PositiveIntegerField()),
                ('sisa', models.PositiveIntegerField()),
                ('pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.pembayaran')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.pembelian')),
            ],
        ),
    ]
