# Generated by Django 5.0 on 2024-02-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0005_alter_returitempembelian_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='tanggal',
            field=models.DateField(auto_created=True),
        ),
    ]
