# Generated by Django 5.0 on 2024-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=50)),
                ('jenis', models.CharField(max_length=50)),
                ('merek', models.CharField(max_length=100)),
                ('tipe', models.CharField(max_length=100)),
                ('ukuran', models.CharField(max_length=50)),
                ('harga_beli', models.PositiveIntegerField()),
                ('harga_jual', models.PositiveIntegerField()),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
    ]
