# Generated by Django 5.0 on 2024-01-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7, unique=True)),
                ('nomor_transaksi', models.CharField(max_length=7)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('stok_awal', models.PositiveIntegerField(default=0)),
                ('masuk', models.PositiveIntegerField(default=0)),
                ('keluar', models.PositiveIntegerField(default=0)),
                ('stok_akhir', models.PositiveIntegerField(default=0)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_stok_barang', to='barang.barang')),
            ],
        ),
    ]
