# Generated by Django 5.0 on 2024-01-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=7)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=225)),
                ('telepon', models.CharField(max_length=13)),
                ('contact_person', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=5)),
                ('rekening', models.CharField(max_length=16)),
            ],
        ),
    ]
