# Generated by Django 5.0 on 2024-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=16)),
                ('bank', models.CharField(max_length=5)),
                ('rekening', models.CharField(max_length=15)),
                ('pic', models.CharField(max_length=100)),
            ],
        ),
    ]
