# Generated by Django 5.0 on 2024-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='nomor',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
